### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by aareben** [kolbyjack/MMM-Dimmer#1]
I can't seem to get this to work. Idk if it's just me, but any help would be great.

**Comment by kolbyjack** [comment]
I'm using locally on my display, so it works for me.  Can you describe your issue?  Post the relevant bits of your config?  Are you able to load your magic mirror in a browser, so you can look at the console for errors?

**Comment by aareben** [comment]
What type of display is this for, just to start? I'm using the ras pi 7-inch display, but neither this nor MMM-ScreenDimmer seems to work. Rly the only issue is that the brightness doesn't change when I start the MM.

**Comment by kolbyjack** [comment]
It's completely independent of the display type.  It uses css to reduce the brightness of the page at night, but doesn't change the actual monitor brightness.

**Comment by aareben** [comment]
Oh ok that makes sense. Ill just try to find another one. The ras pi display uses a specific file to adjust the display brightness, I was trying to find one for that. Thanks
